[changelog]
header = """# Changelog
All notable changes to this project will be documented in this file.

This project adheres to [Keep a Changelog](https://keepachangelog.com/en/1.0.0),
and uses semantic versioning for tags (vMAJOR.MINOR.PATCH).
"""
footer = ""
trim = true

[git]
merge_commits = true
tag_pattern = "^v?\\d+\\.\\d+\\.\\d+$"
filter_commits = true
conventional_commits = true

commit_parsers = [
  { message = "^feat(\\(.+\\))?!?:", group = "Features" },
  { message = "^fix(\\(.+\\))?!?:",  group = "Fixes" },
  { message = "^perf(\\(.+\\))?!?:", group = "Performance" },
  { message = "^refactor(\\(.+\\))?!?:", group = "Refactoring" },
  { message = "^docs(\\(.+\\))?!?:", group = "Docs" },
  { message = "^test(\\(.+\\))?!?:", group = "Tests" },
  { message = "^ci(\\(.+\\))?!?:",   group = "CI" },
  { message = "^build(\\(.+\\))?!?:", group = "Build" },
  { message = "^chore(\\(.+\\))?!?:", group = "Chores" },
  { message = "^Merge pull request",  group = "Merged PRs" },
  { message = ".*",                    group = "Other" },
]

[remote]
github = { owner = "lloydsmart", repo = "chdtool" }
