name: Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "chdtool.sh"
      - "Makefile"
      - "tests/**"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "chdtool.sh"
      - "Makefile"
      - "tests/**"
      - ".github/workflows/tests.yml"

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Install test deps
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip make

      - name: Run tests
        run: make test

      - name: Upload logs from tests (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: logs-from-tests
          path: logs/
          if-no-files-found: ignore
