name: Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "chdtool.sh"
      - "Makefile"
      - "tests/**"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "chdtool.sh"
      - "Makefile"
      - "tests/**"
      - ".github/workflows/tests.yml"

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install test deps
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip make

      - name: Run tests
        run: make test

      - name: Upload logs from tests (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: logs-from-tests
          path: logs/
          if-no-files-found: ignore
